#
# This file was autogenerated edit at your peril
#

package Netscal::BankAccount::Config;

use strict;

use vars qw($valfile $subsfile);

if ( -f "/usr/local/share/Netscal//Valacdos.txt" )
{
   $valfile = "/usr/local/share/Netscal//Valacdos.txt";
}
else
{
   $valfile = "Valacdos.txt";
}

if ( -f "/usr/local/share/Netscal//Scsubtab.txt" )
{
   $subsfile = "/usr/local/share/Netscal//Scsubtab.txt";
}
else
{
   $subsfile = "Scsubtab.txt";
}

1;

