#!/usr/bin/perl -w
#*****************************************************************************
#*                                                                           *
#*                            Netscalibur UK                                 *
#*                                                                           *
#*                                                                           *
#*****************************************************************************
#*                                                                           *
#*      PROGRAM     :  BankAccount                                           *
#*                                                                           *
#*      AUTHOR      :  JNS                                                   *
#*                                                                           *
#*      DESCRIPTION :  SOAP Proxy for Netscal::BankAccount                   *
#*                                                                           *
#*                                                                           *
#*****************************************************************************
#*                                                                           *
#*      $Log: BankAccount,v $
#*      Revision 1.2  2002/04/25 12:11:24  tdcjs
#*      Small changes after made live
#*
#*      Revision 1.1  2002/04/25 10:06:51  tdcjs
#*      Added webservice stuff
#*
#*                                                                           *
#*                                                                           *
#*****************************************************************************

use SOAP::Transport::HTTP; 
use FindBin;

SOAP::Transport::HTTP::CGI
  -> dispatch_to($FindBin::Bin,'Netscal::BankAccount',
                               'Netscal::BankAccount::Config') 
  -> handle() ;
